name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=%23EFE7D2&color_dots=%23262019,%235E322A,%23923F31,%23C2513C,%23ED6F5C
            dist/github-snake-light.svg?color_snake=%232B2B29&color_dots=%23E9E2D1,%23F1C3B6,%23ED9A82,%23EE7D62,%23ED6F5C
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
